apiVersion: v1
kind: Service
metadata:
  name: checker-service
spec:
  selector:                  
    name: checker-daemonset
  ports:
  - port: 4444               
    protocol: TCP
    targetPort: 4444      