apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: checkbot-daemonset
spec:
  selector:
      matchLabels:
        name: checkbot-daemonset 
  template:
    metadata:
      labels:
        name: checkbot-daemonset 
    spec:
      containers:
      - command:
          - ./main
        image: 172.30.1.1:5000/checkbot/checkbot
        imagePullPolicy: Always
        name: checkbot
        ports:
        - containerPort: 4444
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 4444
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 4444
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
      serviceAccount: default
      terminationGracePeriodSeconds: 10