apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: pong-daemonset
spec:
  selector:
      matchLabels:
        name: pong-daemonset 
  template:
    metadata:
      labels:
        name: pong-daemonset 
    spec:
      containers:
      - command:
          - ./main
        image: checkbot/pong
        imagePullPolicy: Always
        name: pong
        ports:
        - containerPort: 4455
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 4455
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 4455
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
      serviceAccount: default
      terminationGracePeriodSeconds: 10