apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: checker-daemonset
spec:
  selector:
      matchLabels:
        name: checker-daemonset 
  template:
    metadata:
      labels:
        name: checker-daemonset 
    spec:
      containers:
      - image: 172.30.1.1:5000/ose-healthchecker/openshift-healthchecker
        imagePullPolicy: Always
        name: healthchecker-1
        ports:
        - containerPort: 4444
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      serviceAccount: default
      terminationGracePeriodSeconds: 10