apiVersion: v1
kind: LimitRange
metadata:
  name: example-limits
spec:
  limits:
    - type: Container
      default:
        cpu: "300m" 
        memory: "200Mi" 
      defaultRequest:
        cpu: "100m" 
        memory: "50Mi" 